create table u (i text primary key, e text not null unique, n text not null, g text not null unique, r text not null default 'u', c integer not null);
create table ss (i text primary key, u text not null, x integer not null);
create table t (i text primary key, n text not null, ab text not null unique, d text not null default '', pr text not null default '#123a6b', lg text);
create table se (i text primary key, n text not null, st text not null default 'a', c integer not null);
create table p (i text primary key, u text, n text not null, t text, j integer, ps text not null default 'c', b text not null default '', h text, st text not null default 'a', c integer not null);
create table g (i text primary key, s text not null, ty text not null default 'r', h text not null, a text not null, hg integer, ag integer, ot text not null default '', dt integer not null, st text not null default 's', rc text);
create table gs (i text primary key, gi text not null, pi text not null, ti text, gl integer not null default 0, a integer not null default 0, pm integer not null default 0, pim integer not null default 0, sog integer not null default 0, hit integer not null default 0, blk integer not null default 0, toi integer not null default 0, fow integer not null default 0, fol integer not null default 0, sv integer, ga integer, sa integer, so integer, r text, unique (gi, pi));
create table at (i text primary key, p text not null, d integer not null, v text not null, no text not null default '');
create table aw (i text primary key, p text not null, n text not null, s text, ty text not null default 'a', d integer not null);
create table pe (i text primary key, p text not null, u text not null, f text not null, v text not null, st text not null default 'r', c integer not null, rv text, rd integer);
create table ns (i text primary key, ti text not null, sl text not null unique, bd text not null, u text not null, pb integer, c integer not null);
create table im (i text primary key, f text not null, k text, n integer not null default 0, st text not null default 'r', er text, u text not null, c integer not null);
create table mp (i text primary key, n text not null, hs text not null unique, v text not null, c integer not null);
create index gs_pi on gs (pi);
create index gs_gi on gs (gi);
create index g_s on g (s, dt);
create index p_t on p (t);
create index at_p on at (p, d);
create index pe_st on pe (st, c);
create index ns_pb on ns (pb);
